resolver: lts-16.31
packages:
- '.'
extra-deps:
- git: git://github.com/dylex/waimwork
  commit: 0ec1caed3aaa4583430484b2b63b5793b94cdb61
- wai-handler-fastcgi-3.0.0.2
- web-inv-route-0.1.3.1
- postgresql-typed-0.6.2.0
flags:
  web-inv-route:
    snap: false
    happstack: false
