resolver: lts-14.11
packages:
- '.'
extra-deps:
- git: git://github.com/dylex/waimwork
  commit: c00627599674ebf19cf5a403bd27c1965051a1c0
- wai-handler-fastcgi-3.0.0.2
- web-inv-route-0.1.2.2
flags:
  web-inv-route:
    snap: false
    happstack: false
