resolver: lts-19.33
packages:
- '.'
extra-deps:
- git: https://github.com/dylex/waimwork
  commit: 8ccaa63ac6b80a4ebc9ad7d61ca38cbb009e8f3c
- web-inv-route-0.1.3.2
flags:
  web-inv-route:
    snap: false
    happstack: false
